version: "3.8"

services:
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongodb_data:/data/db
    localstack:
        image: localstack/localstack:4.0.3
        environment:
            SERVICES: s3,sqs
        ports:
            - 4566:4566
        volumes:
            - ./localstack-script.sh:/etc/localstack/init/ready.d/script.sh
            - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    mongodb_data:
        driver: local
